// Post-build step: copy the Vite output into the pip package's checked-in
// assets (src/lore/viz/assets/) and rewrite dist/index.html into the marker
// template lore/viz/html.py injects into. Run via `npm run build`.
import { copyFileSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const dist = join(here, "..", "dist");
const assets = join(here, "..", "..", "src", "lore", "viz", "assets");

copyFileSync(join(dist, "viz.js"), join(assets, "viz.js"));
copyFileSync(join(dist, "viz.css"), join(assets, "viz.css"));

let html = readFileSync(join(dist, "index.html"), "utf8");
const swaps = [
  [/<script type="module"[^>]*><\/script>/, '<script type="module">/*__LORE_JS__*/</script>'],
  [/<link rel="stylesheet"[^>]*>/, "<style>/*__LORE_CSS__*/</style>"],
];
for (const [pattern, replacement] of swaps) {
  if (!pattern.test(html)) throw new Error(`sync-assets: dist/index.html lost ${pattern}`);
  html = html.replace(pattern, replacement);
}
html = html.replace(
  "<!doctype html>",
  "<!doctype html>\n<!-- GENERATED by viz-ui: edit viz-ui/, then `npm run build`. -->",
);
for (const marker of ["__LORE_TITLE__", "__LORE_SPEC__", "__LORE_TRACE__", "__LORE_SNAPSHOT__", "/*__LORE_CSS__*/", "/*__LORE_JS__*/"]) {
  if (!html.includes(marker)) throw new Error(`sync-assets: template lost marker ${marker}`);
}
writeFileSync(join(assets, "template.html"), html);
console.log(`synced viz.js, viz.css, template.html -> ${assets}`);
